services:
  web:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
    networks:
      - webnet

  python:
    image: python:3
    working_dir: /usr/src/app
    command: python serve.py
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      - webnet

networks:
  webnet:
